In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [2]:
df = pd.read_csv(r"C:\Users\prana\Downloads\archive (3)/covid_toy.csv")

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    df.drop(columns=['has_covid']),
    df['has_covid'],
    test_size=0.2

)

In [6]:
X_train

    age  gender  fever   cough       city
94   79    Male    NaN  Strong    Kolkata
60   24  Female  102.0  Strong  Bangalore
10   75  Female    NaN    Mild      Delhi
95   12  Female  104.0    Mild  Bangalore
80   14  Female   99.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
5    84  Female    NaN    Mild  Bangalore
65   69  Female  102.0    Mild  Bangalore
29   34  Female    NaN  Strong     Mumbai
90   59  Female   99.0  Strong      Delhi
34   74    Male  102.0    Mild     Mumbai

[80 rows x 5 columns]

In [10]:
# adding Simple Imputer to fever column

from sklearn.impute import SimpleImputer

si = SimpleImputer()

X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.transform(X_test[['fever']])

X_train_fever

array([[100.78873239],
       [102.        ],
       [100.78873239],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [100.78873239],
       [102.        ],
       [ 99.        ],
       [101.        ],
       [ 98.        ],
       [ 98.        ],
       [ 99.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [100.78873239],
       [101.        ],
       [102.        ],
       [104.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [104.        ],
       [ 99.        ],
       [102.        ],
       [103.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [104.        ],
       [100.78873239],
       [100.        ],
       [ 99.        ],
       [101.        ],
       [103.        ],
       [104.        ],
       [100.78873239],
       [101.        ],
       [100.        ],
       [100.78873239],
       [101.        ],
       [104.        ],
       [100.        ],
       [104.        ],
       [100.        ],
       [104.        ],
       [ 99.        ],
       [103.        ],
       [102.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ],
       [102.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [103.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [100.        ],
       [101.        ],
       [103.        ],
       [100.78873239],
       [102.        ],
       [100.78873239],
       [ 99.        ],
       [102.        ]])

In [9]:
# Ordinal Encoding -> cough

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Mild', 'Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.transform(X_test[['cough']])

X_train_cough

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [12]:
# One Hot Encoding -> gender, city

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender', 'city']])

# also the test data
X_test_gender_city = ohe.transform(X_test[['gender', 'city']])

X_train_gender_city

array([[1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 1.]])

In [13]:
# Extracting Age

X_train_age = X_train.drop(columns=['gender', 'fever', 'cough', 'city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender', 'fever', 'cough', 'city']).values

X_train_age.shape

(80, 1)

In [21]:
# Concatenating all transformed features

X_train_transformed = np.concatenate(
    (X_train_age, X_train_fever, X_train_gender_city, X_train_cough),
    axis=1
)

# also the test data
X_test_transformed = np.concatenate(
    (X_test_age, X_test_fever, X_test_gender_city, X_test_cough),
    axis=1
)

X_train_transformed.shape

(80, 7)

In [16]:
#With sklearn



from sklearn.compose import ColumnTransformer

In [17]:
transformer = ColumnTransformer(
    transformers=[
        ('tnf1', SimpleImputer(), ['fever']),
        ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
        ('tnf3', OneHotEncoder(drop='first', sparse=False), ['gender', 'city'])
    ],
    remainder='passthrough'
)

In [18]:
X_train_transformed = transformer.fit_transform(X_train)

In [19]:
X_test_transformed = transformer.transform(X_test)

In [20]:
X_train_transformed.shape

(80, 7)