In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv(r"C:\Users\prana\Downloads\archive (1)/customer.csv")

In [51]:
df=df.iloc[:,2:]
df.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [52]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    df.iloc[:,0:2],
    df.iloc[:,-1],
    test_size=0.2

)

In [53]:
X_train

     review education
33     Good        PG
25     Good    School
30  Average        UG
28     Poor    School
37  Average        PG
26     Poor        PG
24  Average        PG
32  Average        UG
22     Poor        PG
5   Average    School
44  Average        UG
49     Good        UG
47     Good        PG
4   Average        UG
6      Good    School
43     Poor        PG
21  Average        PG
40     Good    School
46     Poor        PG
14     Poor        PG
19     Poor        PG
11     Good        UG
0   Average    School
12     Poor    School
1      Poor        UG
35     Poor    School
34  Average    School
42     Good        PG
45     Poor        PG
10     Good        UG
39     Poor        PG
38     Good    School
3      Good        PG
27     Poor        PG
48     Good        UG
2      Good        PG
29  Average        UG
9      Good        UG
31     Poor    School
41     Good        PG

In [54]:
from sklearn.preprocessing import OrdinalEncoder

In [55]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [56]:
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)
X_train

array([[2., 2.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.]])

In [60]:
from sklearn.preprocessing import LabelEncoder

In [61]:
le=LabelEncoder()

In [62]:
le.fit(y_train)

LabelEncoder()

In [63]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [64]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [65]:
y_train

array([1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1])